In [1]:
import numpy as np
import pandas as pd
sbux_clv=pd.read_csv('sbux_clv_drop_AOV_and_completed_offers_across_channels.csv')

In [2]:
sbux_clv.describe()

,Unnamed: 0,MemberSince,Recency (# Days ago from last trans. As of final day up to Day 15),Frequency (# Trans. from Day 1-15),Monetary Value (Sum of Trans. from Day 1-15),# of Marketing offers that Starbucks sent to each customer from Day 1-15,# of Marketing offers that were viewed from Day 1-15,# of Marketing offers that were successfully completed from Day 1-15,Marketing Offer View Rate from Day 1-15,Marketing Offer Response Rate from Day 1-15,Sum(Trans. Amt from Day 16-30)
count,15042.00000,15042.000000,15042.000000,15042.000000,15042.000000,15042.000000,15042.000000,15042.000000,15042.000000,15042.000000,15042.000000
mean,7520.50000,2016.570669,3.008111,3.974139,50.344370,2.253823,1.539955,0.779750,0.678049,0.342318,63.134627
std,4342.39571,1.188821,3.100075,2.668669,73.714738,0.750458,0.843773,0.808312,0.331012,0.354591,88.557657
min,0.00000,2013.000000,0.000000,1.000000,0.050000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,3760.25000,2016.000000,0.000000,2.000000,11.100000,2.000000,1.000000,0.000000,0.500000,0.000000,13.570000
50%,7520.50000,2017.000000,2.000000,3.000000,30.650000,2.000000,2.000000,1.000000,0.670000,0.330000,38.420000
75%,11280.75000,2017.000000,5.000000,5.000000,68.365000,3.000000,2.000000,1.000000,1.000000,0.500000,86.770000
max,15041.00000,2018.000000,14.000000,20.000000,1222.600000,3.000000,3.000000,3.000000,1.000000,1.000000,1287.250000

In [3]:
# Calculate the 95th and 99th percentiles using describe()
percentiles = sbux_clv.describe(percentiles=[0.95, 0.99])

# Print the percentiles
percentiles

,Unnamed: 0,MemberSince,Recency (# Days ago from last trans. As of final day up to Day 15),Frequency (# Trans. from Day 1-15),Monetary Value (Sum of Trans. from Day 1-15),# of Marketing offers that Starbucks sent to each customer from Day 1-15,# of Marketing offers that were viewed from Day 1-15,# of Marketing offers that were successfully completed from Day 1-15,Marketing Offer View Rate from Day 1-15,Marketing Offer Response Rate from Day 1-15,Sum(Trans. Amt from Day 16-30)
count,15042.00000,15042.000000,15042.000000,15042.000000,15042.000000,15042.000000,15042.000000,15042.000000,15042.000000,15042.000000,15042.000000
mean,7520.50000,2016.570669,3.008111,3.974139,50.344370,2.253823,1.539955,0.779750,0.678049,0.342318,63.134627
std,4342.39571,1.188821,3.100075,2.668669,73.714738,0.750458,0.843773,0.808312,0.331012,0.354591,88.557657
min,0.00000,2013.000000,0.000000,1.000000,0.050000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,7520.50000,2017.000000,2.000000,3.000000,30.650000,2.000000,2.000000,1.000000,0.670000,0.330000,38.420000
95%,14288.95000,2018.000000,9.000000,9.000000,142.379000,3.000000,3.000000,2.000000,1.000000,1.000000,171.239000
99%,14890.59000,2018.000000,13.000000,13.000000,261.661900,3.000000,3.000000,3.000000,1.000000,1.000000,468.145700
max,15041.00000,2018.000000,14.000000,20.000000,1222.600000,3.000000,3.000000,3.000000,1.000000,1.000000,1287.250000

###### Anything >= 95% for 'Monetary Value (Sum of Trans. from Day 1-15)' and 'Sum(Trans. Amt from Day 16-30)', impute with 95% number

In [4]:
# Calculate the 95th percentile for the columns
monetary_value_95th = sbux_clv['Monetary Value (Sum of Trans. from Day 1-15)'].quantile(0.95)
trans_amt_95th = sbux_clv['Sum(Trans. Amt from Day 16-30)'].quantile(0.95)

# Impute values equal or above the 95th percentile with the 95th percentile value
sbux_clv['Monetary Value (Sum of Trans. from Day 1-15)'] = sbux_clv['Monetary Value (Sum of Trans. from Day 1-15)'].where(
    sbux_clv['Monetary Value (Sum of Trans. from Day 1-15)'] < monetary_value_95th, monetary_value_95th)
sbux_clv['Sum(Trans. Amt from Day 16-30)'] = sbux_clv['Sum(Trans. Amt from Day 16-30)'].where(
    sbux_clv['Sum(Trans. Amt from Day 16-30)'] < trans_amt_95th, trans_amt_95th)

In [5]:
# Calculate the 95th and 99th percentiles using describe()
percentiles = sbux_clv.describe(percentiles=[0.95, 0.99])

# Print the percentiles
percentiles

,Unnamed: 0,MemberSince,Recency (# Days ago from last trans. As of final day up to Day 15),Frequency (# Trans. from Day 1-15),Monetary Value (Sum of Trans. from Day 1-15),# of Marketing offers that Starbucks sent to each customer from Day 1-15,# of Marketing offers that were viewed from Day 1-15,# of Marketing offers that were successfully completed from Day 1-15,Marketing Offer View Rate from Day 1-15,Marketing Offer Response Rate from Day 1-15,Sum(Trans. Amt from Day 16-30)
count,15042.00000,15042.000000,15042.000000,15042.000000,15042.000000,15042.000000,15042.000000,15042.000000,15042.000000,15042.000000,15042.000000
mean,7520.50000,2016.570669,3.008111,3.974139,44.602129,2.253823,1.539955,0.779750,0.678049,0.342318,55.520546
std,4342.39571,1.188821,3.100075,2.668669,40.852858,0.750458,0.843773,0.808312,0.331012,0.354591,50.249171
min,0.00000,2013.000000,0.000000,1.000000,0.050000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,7520.50000,2017.000000,2.000000,3.000000,30.650000,2.000000,2.000000,1.000000,0.670000,0.330000,38.420000
95%,14288.95000,2018.000000,9.000000,9.000000,142.378050,3.000000,3.000000,2.000000,1.000000,1.000000,171.238050
99%,14890.59000,2018.000000,13.000000,13.000000,142.379000,3.000000,3.000000,3.000000,1.000000,1.000000,171.239000
max,15041.00000,2018.000000,14.000000,20.000000,142.379000,3.000000,3.000000,3.000000,1.000000,1.000000,171.239000

In [6]:
sbux_clv.describe()

,Unnamed: 0,MemberSince,Recency (# Days ago from last trans. As of final day up to Day 15),Frequency (# Trans. from Day 1-15),Monetary Value (Sum of Trans. from Day 1-15),# of Marketing offers that Starbucks sent to each customer from Day 1-15,# of Marketing offers that were viewed from Day 1-15,# of Marketing offers that were successfully completed from Day 1-15,Marketing Offer View Rate from Day 1-15,Marketing Offer Response Rate from Day 1-15,Sum(Trans. Amt from Day 16-30)
count,15042.00000,15042.000000,15042.000000,15042.000000,15042.000000,15042.000000,15042.000000,15042.000000,15042.000000,15042.000000,15042.000000
mean,7520.50000,2016.570669,3.008111,3.974139,44.602129,2.253823,1.539955,0.779750,0.678049,0.342318,55.520546
std,4342.39571,1.188821,3.100075,2.668669,40.852858,0.750458,0.843773,0.808312,0.331012,0.354591,50.249171
min,0.00000,2013.000000,0.000000,1.000000,0.050000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,3760.25000,2016.000000,0.000000,2.000000,11.100000,2.000000,1.000000,0.000000,0.500000,0.000000,13.570000
50%,7520.50000,2017.000000,2.000000,3.000000,30.650000,2.000000,2.000000,1.000000,0.670000,0.330000,38.420000
75%,11280.75000,2017.000000,5.000000,5.000000,68.365000,3.000000,2.000000,1.000000,1.000000,0.500000,86.770000
max,15041.00000,2018.000000,14.000000,20.000000,142.379000,3.000000,3.000000,3.000000,1.000000,1.000000,171.239000

In [7]:
sbux_clv.to_csv('sbux_clv_drop_AOV_and_completed_offers_across_channels_95percent.csv')

In [8]:
# Fill NaNs, zeros, and negative values with a small positive value
sbux_clv['Sum(Trans. Amt from Day 16-30)'].fillna(1e-8, inplace=True)
sbux_clv['Sum(Trans. Amt from Day 16-30)'].replace(0, 1e-8, inplace=True)
sbux_clv['Sum(Trans. Amt from Day 16-30)'].clip(lower=1e-8, inplace=True)

sbux_clv['Monetary Value (Sum of Trans. from Day 1-15)'].fillna(1e-8, inplace=True)
sbux_clv['Monetary Value (Sum of Trans. from Day 1-15)'].replace(0, 1e-8, inplace=True)
sbux_clv['Monetary Value (Sum of Trans. from Day 1-15)'].clip(lower=1e-8, inplace=True)

# Log-transform 'Sum(Trans. Amt from Day 16-30)' column
sbux_clv['Sum(Trans. Amt from Day 16-30)'] = np.log(sbux_clv['Sum(Trans. Amt from Day 16-30)'])

# Log-transform 'Monetary Value (Sum of Trans. from Day 1-15)' column
sbux_clv['Monetary Value (Sum of Trans. from Day 1-15)'] = np.log(sbux_clv['Monetary Value (Sum of Trans. from Day 1-15)'])
sbux_clv.describe()

,Unnamed: 0,MemberSince,Recency (# Days ago from last trans. As of final day up to Day 15),Frequency (# Trans. from Day 1-15),Monetary Value (Sum of Trans. from Day 1-15),# of Marketing offers that Starbucks sent to each customer from Day 1-15,# of Marketing offers that were viewed from Day 1-15,# of Marketing offers that were successfully completed from Day 1-15,Marketing Offer View Rate from Day 1-15,Marketing Offer Response Rate from Day 1-15,Sum(Trans. Amt from Day 16-30)
count,15042.00000,15042.000000,15042.000000,15042.000000,15042.000000,15042.000000,15042.000000,15042.000000,15042.000000,15042.000000,15042.000000
mean,7520.50000,2016.570669,3.008111,3.974139,3.213767,2.253823,1.539955,0.779750,0.678049,0.342318,3.150500
std,4342.39571,1.188821,3.100075,2.668669,1.277718,0.750458,0.843773,0.808312,0.331012,0.354591,2.911019
min,0.00000,2013.000000,0.000000,1.000000,-2.995732,0.000000,0.000000,0.000000,0.000000,0.000000,-18.420681
25%,3760.25000,2016.000000,0.000000,2.000000,2.406945,2.000000,1.000000,0.000000,0.500000,0.000000,2.607861
50%,7520.50000,2017.000000,2.000000,3.000000,3.422633,2.000000,2.000000,1.000000,0.670000,0.330000,3.648578
75%,11280.75000,2017.000000,5.000000,5.000000,4.224861,3.000000,2.000000,1.000000,1.000000,0.500000,4.463261
max,15041.00000,2018.000000,14.000000,20.000000,4.958493,3.000000,3.000000,3.000000,1.000000,1.000000,5.143060

In [9]:
sbux_clv.to_csv('sbux_clv_drop_AOV_and_completed_offers_across_channels_95percent_log_transform.csv')